### ISSUE TITLE
Architecture

### ISSUE THREAD

**Issue by Jacobichou** [rubynoobs/beaker#2]
The way it seems to be set up now will work fine. But I don't feel it is very RoR. What I mean is, the current implied architecture doesn't make use of objects.

Manufacturer's inventories consist of different  types of parts. Thus, we should make use of the associative properties of Rails - parent objects with children. In this case the parent would be a manufacturer who has many parts(children).

**Comment by patrickbrown-dev** [comment]
So in a nutshell:

``` ruby
class Component < ActiveRecord::Base
  belongs_to :supplier
  #...
end
```

and

``` ruby
class Supplier < ActiveRecord::Base
  has_many :components
  #...
end
```

Is this what you mean?

**Comment by Jacobichou** [comment]
Correct.

**Comment by patrickbrown-dev** [comment]
I'm going to close this because we're planning on implementing it this way.
